
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'defNEWLINE STRING TABdef : texttext : line\n                | line NEWLINE textline : STRING\n                | STRING TAB line'
    
_lr_action_items = {'STRING':([0,5,6,],[4,4,4,]),'$end':([1,2,3,4,7,8,],[0,-1,-2,-4,-3,-5,]),'NEWLINE':([3,4,8,],[5,-4,-5,]),'TAB':([4,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'def':([0,],[1,]),'text':([0,5,],[2,7,]),'line':([0,5,6,],[3,3,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> def","S'",1,None,None,None),
  ('def -> text','def',1,'p_file','parser.py',39),
  ('text -> line','text',1,'p_text','parser.py',42),
  ('text -> line NEWLINE text','text',3,'p_text','parser.py',43),
  ('line -> STRING','line',1,'p_line','parser.py',46),
  ('line -> STRING TAB line','line',3,'p_line','parser.py',47),
]
